### ISSUE TITLE
Shiny Dashboard: map hovering

### ISSUE THREAD

**Issue by Sebaristoteles** [Sebaristoteles/sposm_group_assignment#7]
display state/county name while hovering over the map

**Comment by Sebaristoteles** [comment]
Looks amazing!
I just noticed that for "Baden-Württemberg" there are just 2 solar power plants (and low total power) while in the data it is much more. For wind the values are correct.
I was wondering if this because of the Umlaut "ü" that there might be an error. But then it is not clear to me why it should work for wind power.
And ideas?

**Comment by fengzhi22** [comment]
![image](https://user-images.githubusercontent.com/54899895/73166600-7195da00-40f6-11ea-9654-ee5664deb56b.png)
when you merge the two dataset: ger_shape_state and data_state to create map_and_data_state, there emerges two region name identifier: bundesland.x (column 4) and bundesland.y (column 6), which are derivated from ger_shape_state and data_state respectively. In most of the cases they have the same value for each observation, but in some cases they differ. In this map I take bundesland.x as region id, but if I take bundesland.y then the number should be much larger (see second-last observation in the pic). 

Do you have an idea how to consolidate the two region id identifiers?

**Comment by fengzhi22** [comment]
I just checked again, there are really just three observations in which the bundesland.x and bundesland.y differ, probably we just need to adjust it mannually. But since I don't have knowledge about German geography I don't know which identifier is the correct one to take (or should we merge the n, mean and sum of the two identifiers??)... It is great if you could check on observations 13, 62 and 64 in file map_and_data_state. Thanks!

**Comment by Sebaristoteles** [comment]
The inconsistency comes from the source data. The ags-id does in rare cases not correspond to the region-id. Since there was not this kind of inconsistency on a more granular level of subregions, I believe that the region-id is more likely wrong.
I fixed it and uploaded the data files.

**Comment by Sebaristoteles** [comment]
Great work!
